### PR TITLE
feat: third parties

### PR DESCRIPTION
**Pull request by thepassle**
# Todo

- [x] find dependencies list
- [x] `package.json` magic (exports map)
- [x] merge found CEMs
- [ ] remove third-party modules
- [ ] figure out user-friendly logging for the `findDependencies` bit

closes https://github.com/open-wc/custom-elements-manifest/issues/121
closes https://github.com/open-wc/custom-elements-manifest/issues/130
closes https://github.com/open-wc/custom-elements-manifest/issues/123

### CODE REVIEW

**Comment by Westbrook** [comment]
Hey @thepassle how is this PR coming? Would love to see the `--packagejson` option land, so if there's anything I can do to help with that, please let me know!

**Comment by thepassle** [comment]
Still intend on finishing this, but havent had much time recently to work on it.

**Comment by Westbrook** [comment]
Would you be happy/indifferent/annoyed if I reached in for the `package.json` change and submitted a stand alone PR?

**Comment by thepassle** [comment]
The easiest would probably be to finish this PR then, its really not far off. Just need to filter out third party modules at the end and test that everything works as expected

**Comment by Westbrook** [comment]
I can dive in and see if I fully understand what that means and get back to you. Would you have minute to catch this branch up to `master` today or tomorrow to make that easier?

**Comment by thepassle** [comment]
Done

So currently we pick up third party CEMs and we add a `isDependency` property to them so that we can remove them at the end. That still needs to be done.

And otherwise we just need to make sure all the functionality works as expected (e.g. if i extend a class from a third party, is the inheritance output correctly in the CEM? Etc)

I think thats it

**Comment by Westbrook** [comment]
Does that mean that these to dos are already done?
- merge found CEMs
- figure out user-friendly logging for the findDependencies bit

I'll start digging in tomorrow!

**Comment by thepassle** [comment]
Merge found cems is done, logging could be made a bit nicer actually still

**Comment by thepassle** [comment]
this was done in https://github.com/open-wc/custom-elements-manifest/pull/173

**Pull request closed without merging**
