### PR TITLE
feat(analyzer): ignore and internal jsdoc

### LINKED ISSUE #21: support @ignore tag
https://jsdoc.app/tags-ignore.html

> The @ignore tag indicates that a symbol in your code should never appear in the documentation. This tag takes precedence over all others.

Given this source:
```js
const priv = Symbol();
export class MyEl extends HTMLElement {
    f() { return this[priv](); }
    /** @ignore */
    [priv]() { return 'Hi, Pascal!'; }
}
```

I **expect** this output:
```json
{
  "schemaVersion": "0.1.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/my-element.js",
      "declarations": [
        {
          "kind": "class",
          "description": "",
          "name": "MyEl",
          "members": [
            {
              "kind": "method",
              "name": "f"
            }
          ],
          "superclass": {
            "name": "HTMLElement"
          },
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "js",
          "name": "MyEl",
          "declaration": {
            "name": "MyEl",
            "module": "src/my-element.js"
          }
        }
      ]
    }
  ]
}
```

instead **actual** result is:
```json
{
  "schemaVersion": "0.1.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/my-element.js",
      "declarations": [
        {
          "kind": "class",
          "description": "",
          "name": "MyEl",
          "members": [
            {
              "kind": "method",
              "name": "f"
            },
            {
              "kind": "method",
              "name": "[priv]"
            }
          ],
          "superclass": {
            "name": "HTMLElement"
          },
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "js",
          "name": "MyEl",
          "declaration": {
            "name": "MyEl",
            "module": "src/my-element.js"
          }
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #21

### CODE REVIEW

**Comment by bennypowers** [comment]
It's likely i missed some test cases so please look over https://github.com/open-wc/custom-elements-manifest/blob/3c12b0fcb7746692222aa7f597ac86f0a3f7f3f7/packages/analyzer/fixtures/jsdoc-ignore-internal/package/my-element.js#L1-L31

**Comment by thepassle** [comment]
we already had an open PR for this that was almost finished here https://github.com/open-wc/custom-elements-manifest/pull/22

**Comment by bennypowers** [comment]
Ok I covered the case from https://github.com/open-wc/custom-elements-manifest/pull/22#issuecomment-864934707 as well

**Comment by bennypowers** [comment]
I think this is ready to go can you check the test cases please?

**Comment by thepassle** [comment]
Maybe we should revisit the approach we had in this PR https://github.com/open-wc/custom-elements-manifest/pull/22, it solved like 99% of the cases with like 5 lines of code. The only case that needed to be fixed was:
```js
class MyEl extends HTMLElement {
  priv2;

  constructor() {
    super();

    /** @ignore */
    this.priv2 = 'hidden';
  }
}
```

**Comment by bennypowers** [comment]
>  PR #22, it solved like 99% of the cases with like 5 lines 

Unfortunately the previous PR, though brief, did not cover nearly enough cases to be useful, which is why I closed the previous in favour of this one. The reason this PR has to touch so many files is because in many of the handlers, there's no way to remove the `doc` in question without causing reference errors down the pipeline, hence the inclusion of null checks at assignment expressions throughout the core, which I think is anyways a good idea.
 
<details><summary>Test failures on previous branch</summary>

Screen Shot 2021-07-11 at 12 35 07
Screen Shot 2021-07-11 at 12 35 19
Screen Shot 2021-07-11 at 12 35 23


</details>

**Comment by thepassle** [comment]
Those test failures dont seem correct? The implementation in the other branch correctly excluded variables, classes, fields. You're correct that it didnt handle `custom-element-definition`s and `@internal` yet but that would have been trivial to add

**Comment by bennypowers** [comment]
ok i'll give it another look maybe we can have it all

**Pull request closed without merging**
