### PR TITLE
Chore: Add @asdgf/cli as dev dependency

### PR DESCRIPTION
**Pull request by Matsuuu**
Heya,

Noticed that the project uses asdgf to test the project but didn't pack it as a dev dependency at least in the analyzer. Added the package as a dev dep

### CODE REVIEW

**Comment by thepassle** [comment]
Dev dependencies are hoisted in a (yarn workspaces) monorepo, so no need to install it in the package itself

**Comment by Matsuuu** [comment]
Ah gotcha. Just noticed that too yeah.

But that means that you always have to run all of the tests for all of the packages, right? 

Would it hurt to have the import also in the dev deps ofthe package itself?

**Comment by thepassle** [comment]
You can run `yarn` from the monorepo root to install deps, and then you can `cd packages/analyzer` and `yarn test` to only run the tests for that specific package

Id prefer not to add the dep to the package specifically for consistency and to avoid different versions across the monorepo

**Comment by Matsuuu** [comment]
Ah Wasn't aware you could still run the test from the package itself. Yeah let's close this one

**Comment by thepassle** [comment]
Probably should add this info in a CONTRIBUTING.md as well 😅

**Pull request closed without merging**
